import {useTranslations} from 'next-intl';


export default function Page()  {
  const t = useTranslations('default');

  return (
    <div className="layout-dashboard">
      <div className="card text-justify shadow-4">
        <h4>About PLAN4LDN</h4> 
  
        <p className="line-height-3 text-lg">
          The PLAN4LDN tool (Land Use Planning for Land Degradation Neutrality) belongs to the University of Sassari, ICARDA, 
          and WOCAT, who have developed this tool with the technical support of CRS4 by enhancing and reframing the LUP4LDN tool 
          that won the GEO-LDN International Technology Innovation Competition in 2021, and who maintain this tool.
        </p>
        <p className="line-height-3 text-lg ">
          The objective was to design and build software analytics solutions to support more transparent 
          and well-informed land-use decisions at the local to national level across the globe.
        </p>
        <p className="line-height-3 text-lg ">  
          Thus, it aims to feed into innovation and collective action in order to address LDN by including 
          subnational actors and communities in combating land degradation.
        </p>
        <p className="line-height-3 text-lg  "> 
          The competition, guided by a specific framework, included 36 different countries and lasted 5 months,
          from a virtual briefing, virtual pitches (recordings: session 1 and session 2) to arrive at an 
          award ceremony announcing the winners. 
         </p>
         <p className="line-height-3 text-lg "> 
          From a total of 23 proposals, 3 were selected as finalists, including the LUP4LDN tool.
        </p>
        <p className="line-height-3 text-lg  ">   
          After the conclusion of the competition the GEO-LDN Initiative provided funds for the development and piloting of a functioning tool prototype under open access license GNU-GPL v3.0. The prototype was developed by a team composed of Pythagoras Karampiperis and Panagiotis Zervas of IT company SCiO, Quang Bao Le and Enrico Bonaiuti of the International Center for Agricultural Research in the Dry Areas (ICARDA), Claudio Zucca from the University of Sassari (Italy), Tatenda Lemann of the World Overview of Conservation Approaches and Technologies (WOCAT), and Richard Thomas of the Economics for Land Degradation Initiative (ELD). 
        </p>
        <p className="line-height-3 text-lg  ">  
          A functioning prototype version was released in 2023 by IT partner SCiO. Due to insufficient fund availability the released prototype had uncomplete functions only partially reflecting key features included in the science-based conceptual designed and related technical specifications and had no capacity to prevent and/or amend possible inconsistencies generated by user-defined data in order to ensure consistent calculation and mapping of LDN balance.
        </p>
        <p className="line-height-3 text-lg ">  
          In 2024, thanks to funds made available through the PRIMA-funded SOILS4MED project, a team composed of Claudio Zucca of the University of Sassari (Italy) and Quang Bao Le of the International Center for Agricultural Research in the Dry Areas (ICARDA), with IT support from Roberto Demontis of the Center for Advanced Studies, Research and Development in Sardinia (CRS4) has developed an enhanced tool named PLAN4LDN that will be released under the same open access license GNU-GPL v3.0.
          PLAN4LDN uses partially different IT technologies compared to LUP4LDN, has a significantly redesigned interface and implements to a much larger extent the functionalities that form part of the original conceptual design of the tool, including capacity to perform GIS-based processing of input data.
        </p>
        <h5>Technology</h5>
        <p className="line-height-3 text-lg ">
          The tool is now a <a href='https://docs.docker.com/compose/'>docker compose</a> Multi-container application:
        </p>
        <ul className="text-xl p-0 my-0 ml-5">
          <li className="mb-3 line-height-3">
            <h6 className="p-mb-0">Container Nginx (Web Server):</h6>
            - <a href='https://nginx.org'>Nginx</a>: HTTP web server
          </li>	   
          <li className="mb-3 line-height-3">
            <h6 className="p-mb-0">Container Back End (API):</h6> 
            Refactored code from GitHub for new library releases and implementation of the API for Web GIS elaborations<br/>
            - <a href='https://laravel.com/'>Laravel</a>: A php framework for web app,<br/>
            - <a href='https://www.mysql.com/'>MySQL</a>: A Relational Database Management System<br/>
            - <a href='https://gdal.org/'>GDAL library</a>: GIS data elaborations (raster and vector)<br/>  
          </li>
          <li className="mb-3 line-height-3">
            <h6 className="p-mb-0">Container Front End (Web pages):</h6> 
            Refactored code from GitHub for new library releases and created or changed 60% of user interfaces.<br/>
            - <a href='https://react.dev/'>React</a>: A Javascript library<br/>
            - <a href='https://nextjs.org/'>Nextjs</a>: a React Framework for the Web
            - <a href='https://leafletjs.com/'>LeafLet</a>: A JavaScript library for interactive maps<br/>
          </li>
          <li className="mb-3 line-height-3">
            <h6 className="p-mb-0">Container Catalogue (default data management):</h6>  
            A catalogue service for plan4ldn default data.<br/>
            - <a href='https://geonode.org'>Geonode</a>: A Django based Web GIS Catalogue<br/>
            
          </li>
        </ul>
        <h5>Main new features</h5>
        <ol>
          <li className="mb-3 line-height-3">
            User Interface: New web interface with 4 sub-pages and multiple tabs corresponding to common sequences in land-use and management plan, all redesigned for improved, more consistent, and more user-friendly flows (e.g. pages order and page interfaces have functional symbols/features guiding users about steps of use flows).
          </li>
          <li className="mb-3 line-height-3">
            Intermediate outputs: Intermediate maps are generated, exportable, and shown after each processing step, along with tables with surface areas, allowing the user to visually and quantitatively check the effects of land-use/management changes applied step-by-step.
          </li>
          <li className="mb-3 line-height-3">
            Dynamic project update: User can create new focus areas (with multi options such as drawn on web-based map directly, or import shape file), and work on them, after having seen intermediate results and final LDN balance: this change will determine the dynamic update of the entire flow, including the intermediate maps and tables, so that the user’s project can be incrementally developed in time (this was not possible before, when adding a new focus area would require setting up a new project).
          </li>
          <li className="mb-3 line-height-3">
            LU transition matrix: Users can mask/lock particular Land Use (LU) transitions that are not possible (e.g., not allowed by regulation, or obviously unrealistic), making the LU transition matrix better manageable and helping preventing the inclusion of unrealistic transitions
          </li>
          <li className="mb-3 line-height-3">
            Topology: Topological control on polygons uploaded by users to define LU transitions (e.g. areas are not contained in RoI, or areas overlap with other polygons can be cut, then surface areas are recalculated), which keeps the calculation consistent with user’s concrete spatial target.
          </li>
          <li className="mb-3 line-height-3">
            Topology and semantic control: LU changes prescribed through the LU transition matrix are applied only to the intended target use (e.g. if the uploaded polygon hits also other LU type polygons).
          </li>
          <li className="mb-3 line-height-3">
            Planning based LU map: A new, user-created LU map is generated based on the LU changes prescribed through the LU transition matrix and shown as intermediate map, and downloadable.
          </li>
          <li className="mb-3 line-height-3">
            ROI definition: The users can select multiple adjacent administrative units, so they can create sub-national study areas composed of different administrative units (e.g. multiple districts) conforming to their actual planning needs.
          </li>
          <li className="mb-3 line-height-3">
            LDN balance: Procedures and formulas used to calculate the LDN balance have been changed to conform to the UNCCD guidelines (Sims et al., 2021), so that now the tool consistently compares “degraded” areas across business-as-usual and planning-based scenarios generated in consistent output tables and maps.
          </li>
          <li className="mb-3 line-height-3">
            Further changes to the LDN balance procedure needed to integrate the changes introduced by the revised UNCCD guidelines published in December 2024 are in progress.
          </li>
        </ol>
        <h5>References</h5>
        <ul>
          <li className="mb-3 line-height-3">
            <a href='https://wocat.net/en/projects-and-countries/projects/land-use-planning-land-degradation-neutrality-lup4ldn/'>https://wocat.net/en/projects-and-countries/projects/land-use-planning-land-degradation-neutrality-lup4ldn/</a>
          </li>
          <li className="mb-3 line-height-3">
            Sims, N.C., Newnham, G.J., England, J.R., Guerschman, J., Cox, S.J.D., Roxburgh, S.H., Viscarra Rossel, R.A., Fritz, S. and Wheeler, I. 2021. Good Practice Guidance. SDG Indicator 15.3.1, Proportion of Land That Is Degraded Over Total Land Area. Version 2.0. United Nations Convention to Combat Desertification.
          </li>
          <li className="mb-3 line-height-3">
            Bonn, Germany. Zucca C., Le Q. B., Karampiperis P., Lemann T., Thomas R., Thiombiano B. A., Hermassi T., Bonaiuti E., Zervas P., 2023. Toward an operational tool to integrate land degradation neutrality into land use planning: LUP4LDN. Land Degradation and Development 37 (7), 2489-2507. https://doi.org/10.1002/ldr.5075.
          </li>
        </ul>
      </div>
    </div>
    
  );
}

export async function getStaticProps(context) {
  return {
    props: { 
      messages: (await import(`../translations/${context.locale}.json`)).default
     },
  }
}


